spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  main:
    allow-bean-definition-overriding: 'true'

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth:
          starttls:
            enable: true

  datasource:
    driver-class-name: ${DB_CLASS}
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}
  accessTime: ${ACCESS_TIME}
  refreshTime: ${REFRESH_TIME}

server:
  port: 9080